<?php
/**
 * Created by: Merry Roger
 * Date: 01.07.2021
 */


$this->config = [

    'blocks' => 1,
    'contents' => [
        'RQPW' => [
            'provider' => 'newslist',
            'textprovider' => 'tyrion',
            'before' => 0,
            'after' => 0,
            'order' => 'desc',
            'visible' => 3,
            'nopreview' => 'templates.guest.newspage.nopreview'
        ],
    ],

];
