<?php
/**
 * Created by: Merry Roger
 * Date: 01.07.2021
 */


$this->config = [

    'blocks' => 3,
    'contents' => [
        'main_sheet' => [
            'provider' => 'videos',
            'template' => 'templates.guest.videos.main'
        ],
        'left_aside' => [
            'template' => 'templates.empty',
        ],
        'right_aside' => [
            'template' => 'templates.empty',
        ],
    ],

];
